# Generated by Django 5.1.3 on 2024-12-27 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(default='Unknown', max_length=100)),
                ('cast', models.TextField(default='Not Available')),
                ('description', models.TextField(default='No description available')),
                ('release_date', models.DateField(auto_now_add=True)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Science Fiction'), ('Thriller', 'Thriller')], default='Drama', max_length=50)),
                ('language', models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Telugu', 'Telugu'), ('Tamil', 'Tamil'), ('Malayalam', 'Malayalam'), ('Kannada', 'Kannada'), ('Other', 'Other')], default='English', max_length=50)),
                ('duration', models.IntegerField(default=120)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movie_posters/')),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('movie', 'user')},
            },
        ),
    ]
